/*
School21 OpenAPI Specification

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoalitionV1DTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoalitionV1DTO{}

// CoalitionV1DTO Coalition
type CoalitionV1DTO struct {
	// Coalition ID
	CoalitionId int64 `json:"coalitionId"`
	// Coalition name
	Name string `json:"name"`
}

type _CoalitionV1DTO CoalitionV1DTO

// NewCoalitionV1DTO instantiates a new CoalitionV1DTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoalitionV1DTO(coalitionId int64, name string) *CoalitionV1DTO {
	this := CoalitionV1DTO{}
	this.CoalitionId = coalitionId
	this.Name = name
	return &this
}

// NewCoalitionV1DTOWithDefaults instantiates a new CoalitionV1DTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoalitionV1DTOWithDefaults() *CoalitionV1DTO {
	this := CoalitionV1DTO{}
	return &this
}

// GetCoalitionId returns the CoalitionId field value
func (o *CoalitionV1DTO) GetCoalitionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CoalitionId
}

// GetCoalitionIdOk returns a tuple with the CoalitionId field value
// and a boolean to check if the value has been set.
func (o *CoalitionV1DTO) GetCoalitionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CoalitionId, true
}

// SetCoalitionId sets field value
func (o *CoalitionV1DTO) SetCoalitionId(v int64) {
	o.CoalitionId = v
}

// GetName returns the Name field value
func (o *CoalitionV1DTO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CoalitionV1DTO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CoalitionV1DTO) SetName(v string) {
	o.Name = v
}

func (o CoalitionV1DTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoalitionV1DTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["coalitionId"] = o.CoalitionId
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CoalitionV1DTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"coalitionId",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoalitionV1DTO := _CoalitionV1DTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoalitionV1DTO)

	if err != nil {
		return err
	}

	*o = CoalitionV1DTO(varCoalitionV1DTO)

	return err
}

type NullableCoalitionV1DTO struct {
	value *CoalitionV1DTO
	isSet bool
}

func (v NullableCoalitionV1DTO) Get() *CoalitionV1DTO {
	return v.value
}

func (v *NullableCoalitionV1DTO) Set(val *CoalitionV1DTO) {
	v.value = val
	v.isSet = true
}

func (v NullableCoalitionV1DTO) IsSet() bool {
	return v.isSet
}

func (v *NullableCoalitionV1DTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoalitionV1DTO(val *CoalitionV1DTO) *NullableCoalitionV1DTO {
	return &NullableCoalitionV1DTO{value: val, isSet: true}
}

func (v NullableCoalitionV1DTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoalitionV1DTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


