/*
School21 OpenAPI Specification

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ParticipantCourseV1DTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantCourseV1DTO{}

// ParticipantCourseV1DTO Participant Course
type ParticipantCourseV1DTO struct {
	// Course ID
	Id int64 `json:"id"`
	// Course name
	Title string `json:"title"`
	// Course status
	Status string `json:"status"`
	// Final percentage of completion
	FinalPercentage *int32 `json:"finalPercentage,omitempty"`
	// Date and time of the last completion (UTC)
	CompletionDateTime *time.Time `json:"completionDateTime,omitempty"`
}

type _ParticipantCourseV1DTO ParticipantCourseV1DTO

// NewParticipantCourseV1DTO instantiates a new ParticipantCourseV1DTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantCourseV1DTO(id int64, title string, status string) *ParticipantCourseV1DTO {
	this := ParticipantCourseV1DTO{}
	this.Id = id
	this.Title = title
	this.Status = status
	return &this
}

// NewParticipantCourseV1DTOWithDefaults instantiates a new ParticipantCourseV1DTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantCourseV1DTOWithDefaults() *ParticipantCourseV1DTO {
	this := ParticipantCourseV1DTO{}
	return &this
}

// GetId returns the Id field value
func (o *ParticipantCourseV1DTO) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ParticipantCourseV1DTO) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ParticipantCourseV1DTO) SetId(v int64) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *ParticipantCourseV1DTO) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ParticipantCourseV1DTO) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ParticipantCourseV1DTO) SetTitle(v string) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *ParticipantCourseV1DTO) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ParticipantCourseV1DTO) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ParticipantCourseV1DTO) SetStatus(v string) {
	o.Status = v
}

// GetFinalPercentage returns the FinalPercentage field value if set, zero value otherwise.
func (o *ParticipantCourseV1DTO) GetFinalPercentage() int32 {
	if o == nil || IsNil(o.FinalPercentage) {
		var ret int32
		return ret
	}
	return *o.FinalPercentage
}

// GetFinalPercentageOk returns a tuple with the FinalPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantCourseV1DTO) GetFinalPercentageOk() (*int32, bool) {
	if o == nil || IsNil(o.FinalPercentage) {
		return nil, false
	}
	return o.FinalPercentage, true
}

// HasFinalPercentage returns a boolean if a field has been set.
func (o *ParticipantCourseV1DTO) HasFinalPercentage() bool {
	if o != nil && !IsNil(o.FinalPercentage) {
		return true
	}

	return false
}

// SetFinalPercentage gets a reference to the given int32 and assigns it to the FinalPercentage field.
func (o *ParticipantCourseV1DTO) SetFinalPercentage(v int32) {
	o.FinalPercentage = &v
}

// GetCompletionDateTime returns the CompletionDateTime field value if set, zero value otherwise.
func (o *ParticipantCourseV1DTO) GetCompletionDateTime() time.Time {
	if o == nil || IsNil(o.CompletionDateTime) {
		var ret time.Time
		return ret
	}
	return *o.CompletionDateTime
}

// GetCompletionDateTimeOk returns a tuple with the CompletionDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantCourseV1DTO) GetCompletionDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletionDateTime) {
		return nil, false
	}
	return o.CompletionDateTime, true
}

// HasCompletionDateTime returns a boolean if a field has been set.
func (o *ParticipantCourseV1DTO) HasCompletionDateTime() bool {
	if o != nil && !IsNil(o.CompletionDateTime) {
		return true
	}

	return false
}

// SetCompletionDateTime gets a reference to the given time.Time and assigns it to the CompletionDateTime field.
func (o *ParticipantCourseV1DTO) SetCompletionDateTime(v time.Time) {
	o.CompletionDateTime = &v
}

func (o ParticipantCourseV1DTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantCourseV1DTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title
	toSerialize["status"] = o.Status
	if !IsNil(o.FinalPercentage) {
		toSerialize["finalPercentage"] = o.FinalPercentage
	}
	if !IsNil(o.CompletionDateTime) {
		toSerialize["completionDateTime"] = o.CompletionDateTime
	}
	return toSerialize, nil
}

func (o *ParticipantCourseV1DTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"title",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParticipantCourseV1DTO := _ParticipantCourseV1DTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParticipantCourseV1DTO)

	if err != nil {
		return err
	}

	*o = ParticipantCourseV1DTO(varParticipantCourseV1DTO)

	return err
}

type NullableParticipantCourseV1DTO struct {
	value *ParticipantCourseV1DTO
	isSet bool
}

func (v NullableParticipantCourseV1DTO) Get() *ParticipantCourseV1DTO {
	return v.value
}

func (v *NullableParticipantCourseV1DTO) Set(val *ParticipantCourseV1DTO) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantCourseV1DTO) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantCourseV1DTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantCourseV1DTO(val *ParticipantCourseV1DTO) *NullableParticipantCourseV1DTO {
	return &NullableParticipantCourseV1DTO{value: val, isSet: true}
}

func (v NullableParticipantCourseV1DTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantCourseV1DTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


