/*
School21 OpenAPI Specification

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParticipantCampusV1DTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantCampusV1DTO{}

// ParticipantCampusV1DTO Participant Campus
type ParticipantCampusV1DTO struct {
	// Campus ID
	Id string `json:"id"`
	// Short campus name
	ShortName string `json:"shortName"`
}

type _ParticipantCampusV1DTO ParticipantCampusV1DTO

// NewParticipantCampusV1DTO instantiates a new ParticipantCampusV1DTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantCampusV1DTO(id string, shortName string) *ParticipantCampusV1DTO {
	this := ParticipantCampusV1DTO{}
	this.Id = id
	this.ShortName = shortName
	return &this
}

// NewParticipantCampusV1DTOWithDefaults instantiates a new ParticipantCampusV1DTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantCampusV1DTOWithDefaults() *ParticipantCampusV1DTO {
	this := ParticipantCampusV1DTO{}
	return &this
}

// GetId returns the Id field value
func (o *ParticipantCampusV1DTO) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ParticipantCampusV1DTO) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ParticipantCampusV1DTO) SetId(v string) {
	o.Id = v
}

// GetShortName returns the ShortName field value
func (o *ParticipantCampusV1DTO) GetShortName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShortName
}

// GetShortNameOk returns a tuple with the ShortName field value
// and a boolean to check if the value has been set.
func (o *ParticipantCampusV1DTO) GetShortNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShortName, true
}

// SetShortName sets field value
func (o *ParticipantCampusV1DTO) SetShortName(v string) {
	o.ShortName = v
}

func (o ParticipantCampusV1DTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantCampusV1DTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["shortName"] = o.ShortName
	return toSerialize, nil
}

func (o *ParticipantCampusV1DTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"shortName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParticipantCampusV1DTO := _ParticipantCampusV1DTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParticipantCampusV1DTO)

	if err != nil {
		return err
	}

	*o = ParticipantCampusV1DTO(varParticipantCampusV1DTO)

	return err
}

type NullableParticipantCampusV1DTO struct {
	value *ParticipantCampusV1DTO
	isSet bool
}

func (v NullableParticipantCampusV1DTO) Get() *ParticipantCampusV1DTO {
	return v.value
}

func (v *NullableParticipantCampusV1DTO) Set(val *ParticipantCampusV1DTO) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantCampusV1DTO) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantCampusV1DTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantCampusV1DTO(val *ParticipantCampusV1DTO) *NullableParticipantCampusV1DTO {
	return &NullableParticipantCampusV1DTO{value: val, isSet: true}
}

func (v NullableParticipantCampusV1DTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantCampusV1DTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


