/*
School21 OpenAPI Specification

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParticipantSkillV1DTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantSkillV1DTO{}

// ParticipantSkillV1DTO Participant Skill
type ParticipantSkillV1DTO struct {
	// Skill name
	Name string `json:"name"`
	// Skill points
	Points int32 `json:"points"`
}

type _ParticipantSkillV1DTO ParticipantSkillV1DTO

// NewParticipantSkillV1DTO instantiates a new ParticipantSkillV1DTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantSkillV1DTO(name string, points int32) *ParticipantSkillV1DTO {
	this := ParticipantSkillV1DTO{}
	this.Name = name
	this.Points = points
	return &this
}

// NewParticipantSkillV1DTOWithDefaults instantiates a new ParticipantSkillV1DTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantSkillV1DTOWithDefaults() *ParticipantSkillV1DTO {
	this := ParticipantSkillV1DTO{}
	return &this
}

// GetName returns the Name field value
func (o *ParticipantSkillV1DTO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ParticipantSkillV1DTO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ParticipantSkillV1DTO) SetName(v string) {
	o.Name = v
}

// GetPoints returns the Points field value
func (o *ParticipantSkillV1DTO) GetPoints() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *ParticipantSkillV1DTO) GetPointsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Points, true
}

// SetPoints sets field value
func (o *ParticipantSkillV1DTO) SetPoints(v int32) {
	o.Points = v
}

func (o ParticipantSkillV1DTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantSkillV1DTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["points"] = o.Points
	return toSerialize, nil
}

func (o *ParticipantSkillV1DTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"points",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParticipantSkillV1DTO := _ParticipantSkillV1DTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParticipantSkillV1DTO)

	if err != nil {
		return err
	}

	*o = ParticipantSkillV1DTO(varParticipantSkillV1DTO)

	return err
}

type NullableParticipantSkillV1DTO struct {
	value *ParticipantSkillV1DTO
	isSet bool
}

func (v NullableParticipantSkillV1DTO) Get() *ParticipantSkillV1DTO {
	return v.value
}

func (v *NullableParticipantSkillV1DTO) Set(val *ParticipantSkillV1DTO) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantSkillV1DTO) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantSkillV1DTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantSkillV1DTO(val *ParticipantSkillV1DTO) *NullableParticipantSkillV1DTO {
	return &NullableParticipantSkillV1DTO{value: val, isSet: true}
}

func (v NullableParticipantSkillV1DTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantSkillV1DTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


